"""add asset and allocation models + password tokens + categories + users changes

Revision ID: 642f88b332ad
Revises: 10e9385e482c
Create Date: 2025-11-16 00:29:25.990312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642f88b332ad'
down_revision: Union[str, Sequence[str], None] = '10e9385e482c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_alloc_employee_open'), table_name='allocations', postgresql_where='(returned_at IS NULL)')
    op.drop_index(op.f('uq_open_allocation_per_asset'), table_name='allocations', postgresql_where='(returned_at IS NULL)')
    op.drop_index(op.f('idx_return_requests_pending'), table_name='return_requests', postgresql_where='(approved_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_return_requests_pending'), 'return_requests', ['id'], unique=False, postgresql_where='(approved_at IS NULL)')
    op.create_index(op.f('uq_open_allocation_per_asset'), 'allocations', ['asset_id'], unique=True, postgresql_where='(returned_at IS NULL)')
    op.create_index(op.f('idx_alloc_employee_open'), 'allocations', ['employee_id'], unique=False, postgresql_where='(returned_at IS NULL)')
    # ### end Alembic commands ###
